### PR TITLE
Added Unit Tests for Txt Class

### PR DESCRIPTION
**Pull request by paddatrapper**
Added unit tests for Txt and changed the null checks so that
they cannot throw a NullPointerException

### CODE REVIEW

**Comment by mayuso** [comment]
So you found and fixed a bug I did not even know it existed. I knew Testing was really important, but this was just amazing. Thank you :) I need to learn as much as possible about this :)

**Comment by paddatrapper** [comment]
Any time. And now because the tests are there (not very thorough though - ideally they should check the contents of the files and not simply that they exist) any future development that changes Txt can be done safely because the checks are in place to ensure that those changes do not break the pas functionality unintentionally

**Comment by mayuso** [comment]
So if I want to check the content of the files, I can create an example little file and run the tests always on this file? Is that a good practice?

**Comment by paddatrapper** [comment]
No, what you need to do is, in each of the tests that are there 
currently (so after the `assertTrue(f.exisits())`), read the created 
file and check that it parses correctly

**Pull request merged**
